// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.21.11
// source: goods.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateGoodsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGoodsReq) Reset() {
	*x = CreateGoodsReq{}
	mi := &file_goods_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGoodsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGoodsReq) ProtoMessage() {}

func (x *CreateGoodsReq) ProtoReflect() protoreflect.Message {
	mi := &file_goods_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGoodsReq.ProtoReflect.Descriptor instead.
func (*CreateGoodsReq) Descriptor() ([]byte, []int) {
	return file_goods_proto_rawDescGZIP(), []int{0}
}

type CreateGoodsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGoodsResp) Reset() {
	*x = CreateGoodsResp{}
	mi := &file_goods_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGoodsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGoodsResp) ProtoMessage() {}

func (x *CreateGoodsResp) ProtoReflect() protoreflect.Message {
	mi := &file_goods_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGoodsResp.ProtoReflect.Descriptor instead.
func (*CreateGoodsResp) Descriptor() ([]byte, []int) {
	return file_goods_proto_rawDescGZIP(), []int{1}
}

var File_goods_proto protoreflect.FileDescriptor

const file_goods_proto_rawDesc = "" +
	"\n" +
	"\vgoods.proto\x12\x06Proto3\"\x10\n" +
	"\x0eCreateGoodsReq\"\x11\n" +
	"\x0fCreateGoodsResp2M\n" +
	"\vGoodsServer\x12>\n" +
	"\vCreateGoods\x12\x16.Proto3.CreateGoodsReq\x1a\x17.Proto3.CreateGoodsRespB\x03Z\x01/b\x06proto3"

var (
	file_goods_proto_rawDescOnce sync.Once
	file_goods_proto_rawDescData []byte
)

func file_goods_proto_rawDescGZIP() []byte {
	file_goods_proto_rawDescOnce.Do(func() {
		file_goods_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_goods_proto_rawDesc), len(file_goods_proto_rawDesc)))
	})
	return file_goods_proto_rawDescData
}

var file_goods_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_goods_proto_goTypes = []any{
	(*CreateGoodsReq)(nil),  // 0: Proto3.CreateGoodsReq
	(*CreateGoodsResp)(nil), // 1: Proto3.CreateGoodsResp
}
var file_goods_proto_depIdxs = []int32{
	0, // 0: Proto3.GoodsServer.CreateGoods:input_type -> Proto3.CreateGoodsReq
	1, // 1: Proto3.GoodsServer.CreateGoods:output_type -> Proto3.CreateGoodsResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_goods_proto_init() }
func file_goods_proto_init() {
	if File_goods_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_goods_proto_rawDesc), len(file_goods_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_goods_proto_goTypes,
		DependencyIndexes: file_goods_proto_depIdxs,
		MessageInfos:      file_goods_proto_msgTypes,
	}.Build()
	File_goods_proto = out.File
	file_goods_proto_goTypes = nil
	file_goods_proto_depIdxs = nil
}
