// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.11
// source: goods.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GoodsServer_CreateGoods_FullMethodName = "/Proto3.GoodsServer/CreateGoods"
)

// GoodsServerClient is the client API for GoodsServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GoodsServerClient interface {
	CreateGoods(ctx context.Context, in *CreateGoodsReq, opts ...grpc.CallOption) (*CreateGoodsResp, error)
}

type goodsServerClient struct {
	cc grpc.ClientConnInterface
}

func NewGoodsServerClient(cc grpc.ClientConnInterface) GoodsServerClient {
	return &goodsServerClient{cc}
}

func (c *goodsServerClient) CreateGoods(ctx context.Context, in *CreateGoodsReq, opts ...grpc.CallOption) (*CreateGoodsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateGoodsResp)
	err := c.cc.Invoke(ctx, GoodsServer_CreateGoods_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GoodsServerServer is the server API for GoodsServer service.
// All implementations must embed UnimplementedGoodsServerServer
// for forward compatibility.
type GoodsServerServer interface {
	CreateGoods(context.Context, *CreateGoodsReq) (*CreateGoodsResp, error)
	mustEmbedUnimplementedGoodsServerServer()
}

// UnimplementedGoodsServerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGoodsServerServer struct{}

func (UnimplementedGoodsServerServer) CreateGoods(context.Context, *CreateGoodsReq) (*CreateGoodsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateGoods not implemented")
}
func (UnimplementedGoodsServerServer) mustEmbedUnimplementedGoodsServerServer() {}
func (UnimplementedGoodsServerServer) testEmbeddedByValue()                     {}

// UnsafeGoodsServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GoodsServerServer will
// result in compilation errors.
type UnsafeGoodsServerServer interface {
	mustEmbedUnimplementedGoodsServerServer()
}

func RegisterGoodsServerServer(s grpc.ServiceRegistrar, srv GoodsServerServer) {
	// If the following call pancis, it indicates UnimplementedGoodsServerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GoodsServer_ServiceDesc, srv)
}

func _GoodsServer_CreateGoods_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGoodsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoodsServerServer).CreateGoods(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoodsServer_CreateGoods_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoodsServerServer).CreateGoods(ctx, req.(*CreateGoodsReq))
	}
	return interceptor(ctx, in, info, handler)
}

// GoodsServer_ServiceDesc is the grpc.ServiceDesc for GoodsServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GoodsServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Proto3.GoodsServer",
	HandlerType: (*GoodsServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateGoods",
			Handler:    _GoodsServer_CreateGoods_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "goods.proto",
}
